// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileListRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Recursive            bool     `protobuf:"varint,2,opt,name=Recursive,proto3" json:"Recursive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileListRequest) Reset()         { *m = FileListRequest{} }
func (m *FileListRequest) String() string { return proto.CompactTextString(m) }
func (*FileListRequest) ProtoMessage()    {}
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *FileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileListRequest.Unmarshal(m, b)
}
func (m *FileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileListRequest.Marshal(b, m, deterministic)
}
func (m *FileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileListRequest.Merge(m, src)
}
func (m *FileListRequest) XXX_Size() int {
	return xxx_messageInfo_FileListRequest.Size(m)
}
func (m *FileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileListRequest proto.InternalMessageInfo

func (m *FileListRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *FileListRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

type FileListResponse struct {
	Base                 string            `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Files                []*FileDescriptor `protobuf:"bytes,2,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FileListResponse) Reset()         { *m = FileListResponse{} }
func (m *FileListResponse) String() string { return proto.CompactTextString(m) }
func (*FileListResponse) ProtoMessage()    {}
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *FileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileListResponse.Unmarshal(m, b)
}
func (m *FileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileListResponse.Marshal(b, m, deterministic)
}
func (m *FileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileListResponse.Merge(m, src)
}
func (m *FileListResponse) XXX_Size() int {
	return xxx_messageInfo_FileListResponse.Size(m)
}
func (m *FileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileListResponse proto.InternalMessageInfo

func (m *FileListResponse) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *FileListResponse) GetFiles() []*FileDescriptor {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileDescriptor struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
	IsDirectory          bool     `protobuf:"varint,2,opt,name=IsDirectory,proto3" json:"IsDirectory,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDescriptor) Reset()         { *m = FileDescriptor{} }
func (m *FileDescriptor) String() string { return proto.CompactTextString(m) }
func (*FileDescriptor) ProtoMessage()    {}
func (*FileDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *FileDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDescriptor.Unmarshal(m, b)
}
func (m *FileDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDescriptor.Marshal(b, m, deterministic)
}
func (m *FileDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDescriptor.Merge(m, src)
}
func (m *FileDescriptor) XXX_Size() int {
	return xxx_messageInfo_FileDescriptor.Size(m)
}
func (m *FileDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_FileDescriptor proto.InternalMessageInfo

func (m *FileDescriptor) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *FileDescriptor) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *FileDescriptor) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileReadRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
	Position             uint64   `protobuf:"varint,2,opt,name=Position,proto3" json:"Position,omitempty"`
	MaxSize              uint64   `protobuf:"varint,3,opt,name=MaxSize,proto3" json:"MaxSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReadRequest) Reset()         { *m = FileReadRequest{} }
func (m *FileReadRequest) String() string { return proto.CompactTextString(m) }
func (*FileReadRequest) ProtoMessage()    {}
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *FileReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReadRequest.Unmarshal(m, b)
}
func (m *FileReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReadRequest.Marshal(b, m, deterministic)
}
func (m *FileReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReadRequest.Merge(m, src)
}
func (m *FileReadRequest) XXX_Size() int {
	return xxx_messageInfo_FileReadRequest.Size(m)
}
func (m *FileReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileReadRequest proto.InternalMessageInfo

func (m *FileReadRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *FileReadRequest) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *FileReadRequest) GetMaxSize() uint64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

type FileReadResponse struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
	Position             uint64   `protobuf:"varint,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	EOF                  bool     `protobuf:"varint,4,opt,name=EOF,proto3" json:"EOF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReadResponse) Reset()         { *m = FileReadResponse{} }
func (m *FileReadResponse) String() string { return proto.CompactTextString(m) }
func (*FileReadResponse) ProtoMessage()    {}
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *FileReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReadResponse.Unmarshal(m, b)
}
func (m *FileReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReadResponse.Marshal(b, m, deterministic)
}
func (m *FileReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReadResponse.Merge(m, src)
}
func (m *FileReadResponse) XXX_Size() int {
	return xxx_messageInfo_FileReadResponse.Size(m)
}
func (m *FileReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileReadResponse proto.InternalMessageInfo

func (m *FileReadResponse) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *FileReadResponse) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *FileReadResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *FileReadResponse) GetEOF() bool {
	if m != nil {
		return m.EOF
	}
	return false
}

type FileWriteRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
	Overwrite            bool     `protobuf:"varint,2,opt,name=Overwrite,proto3" json:"Overwrite,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileWriteRequest) Reset()         { *m = FileWriteRequest{} }
func (m *FileWriteRequest) String() string { return proto.CompactTextString(m) }
func (*FileWriteRequest) ProtoMessage()    {}
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5}
}

func (m *FileWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileWriteRequest.Unmarshal(m, b)
}
func (m *FileWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileWriteRequest.Marshal(b, m, deterministic)
}
func (m *FileWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileWriteRequest.Merge(m, src)
}
func (m *FileWriteRequest) XXX_Size() int {
	return xxx_messageInfo_FileWriteRequest.Size(m)
}
func (m *FileWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileWriteRequest proto.InternalMessageInfo

func (m *FileWriteRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *FileWriteRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

func (m *FileWriteRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FileWriteResponse struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileWriteResponse) Reset()         { *m = FileWriteResponse{} }
func (m *FileWriteResponse) String() string { return proto.CompactTextString(m) }
func (*FileWriteResponse) ProtoMessage()    {}
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{6}
}

func (m *FileWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileWriteResponse.Unmarshal(m, b)
}
func (m *FileWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileWriteResponse.Marshal(b, m, deterministic)
}
func (m *FileWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileWriteResponse.Merge(m, src)
}
func (m *FileWriteResponse) XXX_Size() int {
	return xxx_messageInfo_FileWriteResponse.Size(m)
}
func (m *FileWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileWriteResponse proto.InternalMessageInfo

func (m *FileWriteResponse) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *FileWriteResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*FileListRequest)(nil), "file.FileListRequest")
	proto.RegisterType((*FileListResponse)(nil), "file.FileListResponse")
	proto.RegisterType((*FileDescriptor)(nil), "file.FileDescriptor")
	proto.RegisterType((*FileReadRequest)(nil), "file.FileReadRequest")
	proto.RegisterType((*FileReadResponse)(nil), "file.FileReadResponse")
	proto.RegisterType((*FileWriteRequest)(nil), "file.FileWriteRequest")
	proto.RegisterType((*FileWriteResponse)(nil), "file.FileWriteResponse")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x6d, 0xda, 0xec, 0x6e, 0x33, 0x5d, 0xed, 0x16, 0x8b, 0x8f, 0x28, 0xea, 0x21, 0xf2, 0x29,
	0xe2, 0xd0, 0x43, 0x39, 0x22, 0x71, 0xa0, 0xa5, 0x12, 0x12, 0xa8, 0xc8, 0x1c, 0x38, 0xa7, 0x61,
	0x2a, 0x2c, 0x55, 0x71, 0xb0, 0xdd, 0xf2, 0xf1, 0xeb, 0xf8, 0x69, 0xc8, 0x49, 0x9d, 0x98, 0x4f,
	0x55, 0xe2, 0x36, 0xf3, 0x32, 0xe3, 0x37, 0x6f, 0xde, 0x04, 0x60, 0xc1, 0x97, 0x38, 0x2c, 0xa4,
	0xd0, 0x82, 0xf8, 0x26, 0xa6, 0x63, 0xf8, 0x3f, 0xe5, 0x4b, 0xbc, 0xe0, 0x4a, 0x33, 0xbc, 0x5f,
	0xa1, 0xd2, 0x84, 0x80, 0x7f, 0x9a, 0x2a, 0x0c, 0xbd, 0xd8, 0x4b, 0x02, 0x56, 0xc6, 0x64, 0x00,
	0x01, 0xc3, 0x6c, 0x25, 0x15, 0x5f, 0x63, 0xd8, 0x8e, 0xbd, 0xa4, 0xcb, 0x1a, 0x80, 0x32, 0xe8,
	0x37, 0x8f, 0xa8, 0x42, 0xe4, 0x0a, 0x3f, 0x7d, 0xe5, 0x10, 0x7e, 0x99, 0x3a, 0x15, 0xb6, 0xe3,
	0x4e, 0xd2, 0x1b, 0xed, 0x0e, 0xcb, 0x71, 0x0c, 0x34, 0x41, 0x95, 0x49, 0x5e, 0x68, 0x21, 0x59,
	0x55, 0x42, 0xe7, 0xf0, 0xef, 0xed, 0x07, 0x12, 0x41, 0xd7, 0x20, 0x45, 0xaa, 0xef, 0x36, 0xaf,
	0xd6, 0x39, 0x89, 0xa1, 0x77, 0xae, 0x26, 0x5c, 0x62, 0xa6, 0x85, 0x7c, 0xda, 0x4c, 0xe8, 0x42,
	0x66, 0x9e, 0x6b, 0xfe, 0x8c, 0x61, 0x27, 0xf6, 0x12, 0x9f, 0x95, 0x31, 0xcd, 0x2a, 0xf1, 0x0c,
	0xd3, 0x5b, 0x2b, 0xfe, 0x3b, 0x92, 0x08, 0xba, 0x57, 0x42, 0x71, 0xcd, 0x45, 0x5e, 0x32, 0xf8,
	0xac, 0xce, 0x49, 0x08, 0x7f, 0x2e, 0xd3, 0x47, 0x87, 0xc1, 0xa6, 0x74, 0x5d, 0x2d, 0xa7, 0x22,
	0xd9, 0x2c, 0xe7, 0x07, 0x2c, 0x63, 0x91, 0x6b, 0xcc, 0x75, 0xc9, 0xf2, 0x97, 0xd9, 0x94, 0xf4,
	0xa1, 0x73, 0x36, 0x9b, 0x86, 0x7e, 0x29, 0xdc, 0x84, 0x74, 0x51, 0xf1, 0xde, 0x48, 0xae, 0x71,
	0x1b, 0x75, 0x03, 0x08, 0x66, 0x6b, 0x94, 0x0f, 0xa6, 0xde, 0x5a, 0x5c, 0x03, 0x5f, 0x33, 0xd3,
	0x31, 0xec, 0x38, 0x3c, 0x5b, 0x08, 0xb4, 0x4e, 0xb4, 0x1b, 0x27, 0x46, 0x2f, 0x1e, 0xf8, 0xa6,
	0x80, 0x1c, 0x57, 0x8d, 0xe6, 0x94, 0xc8, 0x5e, 0x73, 0x1f, 0xce, 0x7d, 0x46, 0xfb, 0xef, 0xe1,
	0x8a, 0x93, 0xb6, 0x6c, 0xb3, 0x59, 0xb5, 0xdb, 0xec, 0xf8, 0xeb, 0x36, 0xbb, 0x8e, 0xd0, 0x16,
	0x39, 0x81, 0xa0, 0xd6, 0x41, 0x9c, 0x32, 0x77, 0x81, 0xd1, 0xc1, 0x07, 0xdc, 0xf6, 0xcf, 0x7f,
	0x97, 0xbf, 0xd5, 0xd1, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x3a, 0x51, 0xea, 0x64, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileClient interface {
	FileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListResponse, error)
	FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error)
	FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error)
}

type fileClient struct {
	cc *grpc.ClientConn
}

func NewFileClient(cc *grpc.ClientConn) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) FileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListResponse, error) {
	out := new(FileListResponse)
	err := c.cc.Invoke(ctx, "/file.File/FileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error) {
	out := new(FileReadResponse)
	err := c.cc.Invoke(ctx, "/file.File/FileRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error) {
	out := new(FileWriteResponse)
	err := c.cc.Invoke(ctx, "/file.File/FileWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServer is the server API for File service.
type FileServer interface {
	FileList(context.Context, *FileListRequest) (*FileListResponse, error)
	FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error)
	FileWrite(context.Context, *FileWriteRequest) (*FileWriteResponse, error)
}

// UnimplementedFileServer can be embedded to have forward compatible implementations.
type UnimplementedFileServer struct {
}

func (*UnimplementedFileServer) FileList(ctx context.Context, req *FileListRequest) (*FileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileList not implemented")
}
func (*UnimplementedFileServer) FileRead(ctx context.Context, req *FileReadRequest) (*FileReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRead not implemented")
}
func (*UnimplementedFileServer) FileWrite(ctx context.Context, req *FileWriteRequest) (*FileWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileWrite not implemented")
}

func RegisterFileServer(s *grpc.Server, srv FileServer) {
	s.RegisterService(&_File_serviceDesc, srv)
}

func _File_FileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).FileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.File/FileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).FileList(ctx, req.(*FileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_FileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).FileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.File/FileRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).FileRead(ctx, req.(*FileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_FileWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).FileWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.File/FileWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).FileWrite(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _File_serviceDesc = grpc.ServiceDesc{
	ServiceName: "file.File",
	HandlerType: (*FileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileList",
			Handler:    _File_FileList_Handler,
		},
		{
			MethodName: "FileRead",
			Handler:    _File_FileRead_Handler,
		},
		{
			MethodName: "FileWrite",
			Handler:    _File_FileWrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file.proto",
}
